# Generated by Django 2.2.8 on 2019-12-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentvalidate',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentvote',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
