# Generated by Django 2.2.8 on 2020-01-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_assignment'),
        ('pages', '0007_auto_20200105_2115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.TaskData', verbose_name='task_id'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='tasker_id'),
        ),
    ]
