# Generated by Django 2.2.8 on 2020-01-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0004_auto_20200105_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentvote',
            name='task',
        ),
        migrations.RemoveField(
            model_name='assignmentvote',
            name='tasker',
        ),
        migrations.DeleteModel(
            name='AssignmentValidate',
        ),
        migrations.DeleteModel(
            name='AssignmentVote',
        ),
    ]
