language: python

python:
 - "3.7"

services:
 - postgresql

env:
 - DJANGO=2.2.8

install:
 - pip install -r requirements.txt
 - pip install django==$DJANGO --quiet
 - pip install psycopg2 --quiet
 - pip install coverage

after_success:
  - codecov

script:
- python manage.py test

branches:
  only:
    - master
