language: python

python:
 - "3.7"

services:
 - postgresql

env:
 - DJANGO=2.2.8

install:
 - pip install -r requirements.txt --quiet
 - pip install django==$DJANGO --quiet
 - pip install psycopg2 --quiet
 - pip install codecov --quiet

addons:
  chrome: stable

script:
- python manage.py test

branches:
  only:
    - master
    - develop

after_success:
 - codecov
