language: python

python:
 - "3.7"

services:
 - postgresql

env:
 - DJANGO=2.2.8

install:
 - pip install -r requirements.txt --quiet
 - pip install django==$DJANGO --quiet
 - pip install psycopg2 --quiet
 - pip install codecov --quiet

addons:
  chrome: stable

before_script:
- LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
- curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.7.1/bin/
- export CHROME_BIN=chromium-browser
- psql -c 'create database datacleansing;'
- python manage.py migrate
- python manage.py loaddata fixtures.json

script:
- coverage run --source=. manage.py test

branches:
  only:
    - master
    - develop

after_success:
 - codecov