# Generated by Django 2.2.8 on 2020-01-21 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_auto_20200117_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.CustomGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ValidatingData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Data')),
                ('answer_text', models.TextField()),
                ('num_approved', models.IntegerField(default=0)),
                ('num_disapproved', models.IntegerField(default=0)),
            ],
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='VotingData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Data')),
                ('is_active', models.BooleanField(default=False)),
            ],
            bases=('pages.data',),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('checked', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('num_votes', models.IntegerField(default=0)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.VotingData')),
            ],
        ),
    ]
