# Generated by Django 2.2.8 on 2020-01-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200118_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizeddata',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
