# Generated by Django 2.2.8 on 2020-01-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200117_1647'),
        ('pages', '0002_finalizeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='data',
            unique_together={('title', 'group')},
        ),
    ]
