# Generated by Django 2.2.8 on 2020-01-25 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200121_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.CustomGroup'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='data_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validatingdata',
            name='data_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Data'),
        ),
        migrations.AlterField(
            model_name='votingdata',
            name='data_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Data'),
        ),
    ]
