# Generated by Django 2.2.5 on 2019-12-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191216_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='type_text',
        ),
        migrations.RemoveField(
            model_name='votingdata',
            name='type_text',
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Type'),
        ),
        migrations.AddField(
            model_name='votingdata',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Type'),
        ),
    ]
