# Generated by Django 2.2.8 on 2020-02-12 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200125_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizeddata',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Data'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
