# Generated by Django 2.2.8 on 2020-02-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20200212_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalizeddata',
            old_name='keywords',
            new_name='ans_keywords',
        ),
        migrations.AddField(
            model_name='finalizeddata',
            name='qns_keywords',
            field=models.TextField(null=True),
        ),
    ]
