# Generated by Django 2.2.5 on 2019-12-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191217_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingdata',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
