# Generated by Django 2.2.8 on 2020-01-05 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0003_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0006_votingdata_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='validatingdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='validatingdata',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='votingdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='votingdata',
            name='question_text',
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='assign.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='validatingdata',
            name='question_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='validating_question', serialize=False, to='pages.TaskData'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votingdata',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='voting_question', serialize=False, to='pages.TaskData'),
            preserve_default=False,
        ),
    ]
