# Generated by Django 2.2.8 on 2020-02-19 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200219_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedImageData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Data')),
                ('image_url', models.URLField(unique=True)),
            ],
            bases=('pages.data',),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='image_url',
            field=models.URLField(unique=True),
        ),
    ]
