# Generated by Django 2.2.8 on 2020-01-05 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20200105_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validatingdata',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='votingdata',
            old_name='question_id',
            new_name='question',
        ),
        migrations.AlterField(
            model_name='choice',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.VotingData', to_field='question_id'),
        ),
    ]
