# Generated by Django 2.2.8 on 2020-02-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200219_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalizedimagedata',
            name='label',
            field=models.CharField(default='Lable', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagelabel',
            name='label',
            field=models.CharField(max_length=200),
        ),
    ]
