# Generated by Django 2.2.8 on 2020-01-13 03:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200105_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='status',
            new_name='action',
        ),
        migrations.AddField(
            model_name='log',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='response',
            field=models.TextField(default='vote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 3, 44, 32, 418892)),
        ),
        migrations.AlterField(
            model_name='choice',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.VotingData'),
        ),
    ]
