# Generated by Django 2.2.8 on 2020-01-15 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200113_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 4, 25, 24, 30652)),
        ),
    ]
