# Generated by Django 2.2.8 on 2020-04-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200223_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingdata',
            name='num_votes',
            field=models.IntegerField(default=0),
        ),
    ]
