# Generated by Django 2.2.8 on 2020-01-15 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200115_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votingdata',
            old_name='activate',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 4, 36, 9, 242126)),
        ),
    ]
