# Generated by Django 2.2.8 on 2020-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_imagedata_num_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='is_contro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votingdata',
            name='is_contro',
            field=models.BooleanField(default=False),
        ),
    ]
