# Generated by Django 2.2.8 on 2020-01-16 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20200115_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 6, 53, 51, 270069)),
        ),
    ]
