# Generated by Django 2.2.5 on 2019-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('authentication', '0002_auto_20191212_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='speicialization',
            field=models.ManyToManyField(to='authentication.Specialization'),
        ),
    ]
