# Generated by Django 2.2.8 on 2020-01-25 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200117_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ACTIVATE', 'activate'), ('DEACTIVATE', 'deactivate'), ('APPROVE', 'approve'), ('REJECT', 'reject')], max_length=32)),
                ('extra_msg', models.TextField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_history', to=settings.AUTH_USER_MODEL)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
