# Generated by Django 2.2.5 on 2019-12-18 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0003_auto_20191217_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='speicialization',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='groups',
        ),
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('main_group',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Specialization')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='authentication.CustomGroup'),
        ),
    ]
