# Generated by Django 2.2.8 on 2020-03-15 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200125_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
