# Generated by Django 2.2.5 on 2019-12-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0004_auto_20191218_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accuracy',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
