# Generated by Django 2.2.8 on 2019-12-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0005_auto_20191218_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False,
                                      help_text='Designates whether the user can log into this admin site.',
                                      verbose_name='staff status'),
        ),
    ]
