# Generated by Django 2.2.8 on 2019-12-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20191218_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_ans',
            field=models.IntegerField(default=0),
        ),
    ]
