# Generated by Django 2.2.8 on 2019-12-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_num_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='customuser',
            name='correct_num_ans',
            field=models.IntegerField(default=0),
        ),
    ]
