# Generated by Django 2.2.8 on 2020-01-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0011_auto_20191225_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
